# Generated by Django 3.2.4 on 2021-06-19 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0003_auto_20210619_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='graduatingYear',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
