# Generated by Django 3.2.4 on 2021-06-20 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0004_alter_user_graduatingyear'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='branchName',
            new_name='branch_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='organizationName',
            new_name='organization_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='graduatingYear',
            new_name='program_duration',
        ),
        migrations.RemoveField(
            model_name='user',
            name='detail',
        ),
        migrations.RemoveField(
            model_name='user',
            name='prerequisites',
        ),
        migrations.RemoveField(
            model_name='user',
            name='skill',
        ),
        migrations.RemoveField(
            model_name='user',
            name='tags',
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(blank=True, max_length=50)),
                ('detail', models.ManyToManyField(blank=True, related_name='all_skills_with_this_topic', to='form.Topic')),
                ('prerequisites', models.ManyToManyField(blank=True, related_name='all_skills_with_this_prerequisite', to='form.Prerequisite')),
                ('tags', models.ManyToManyField(blank=True, related_name='all_skills_with_this_tag', to='form.Tag')),
            ],
        ),
    ]
