# Generated by Django 3.2.4 on 2021-06-20 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0005_auto_20210620_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='contributed_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='form.user'),
            preserve_default=False,
        ),
    ]
