# Generated by Django 3.2.4 on 2021-06-28 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0008_super_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='super_skill',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='super_skills_with_this_tag', to='form.Tag'),
        ),
    ]
