# Generated by Django 3.2.4 on 2021-06-28 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0009_super_skill_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='super_skill',
            name='sub_skills',
            field=models.ManyToManyField(blank=True, related_name='super_skill', to='form.Skill'),
        ),
    ]
