# Generated by Django 3.2.4 on 2021-07-20 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0011_super_skill_contributed_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='detail',
            new_name='topics',
        ),
        migrations.AddField(
            model_name='skill',
            name='userName',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
