# Generated by Django 3.2.4 on 2021-08-16 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0013_auto_20210815_2330'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='value',
            new_name='link',
        ),
    ]
