# Generated by Django 3.2.4 on 2021-08-17 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0014_rename_value_resource_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='super_skill',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, related_name='all_super_skills_with_this_prerequisite', to='form.Prerequisite'),
        ),
    ]
