# Generated by Django 3.2.4 on 2021-08-19 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0015_super_skill_prerequisites'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='userName',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='userName',
        ),
    ]
