# Generated by Django 3.2.4 on 2021-10-26 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0016_auto_20210820_0021'),
    ]

    operations = [
        migrations.CreateModel(
            name='Super_skill_edit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on_id', models.PositiveBigIntegerField()),
                ('name', models.CharField(blank=True, max_length=50)),
                ('contributed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='form.user')),
                ('prerequisites', models.ManyToManyField(blank=True, to='form.Prerequisite')),
                ('sub_skills', models.ManyToManyField(blank=True, to='form.Skill')),
                ('tags', models.ManyToManyField(blank=True, to='form.Tag')),
            ],
        ),
    ]
