# Generated by Django 3.2.4 on 2021-11-25 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0017_super_skill_edit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='topics',
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('levelName', models.TextField(blank=True)),
                ('topics', models.ManyToManyField(blank=True, related_name='topic_level', to='form.Topic')),
            ],
        ),
        migrations.AddField(
            model_name='skill',
            name='levels',
            field=models.ManyToManyField(blank=True, related_name='all_skills_with_this_level', to='form.Level'),
        ),
    ]
