# Generated by Django 3.2.4 on 2021-11-28 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0020_auto_20211126_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='language',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
