# Generated by Django 3.2.4 on 2021-11-28 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0021_skill_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=50)),
                ('message', models.TextField(blank=True)),
            ],
        ),
    ]
