# Generated by Django 3.2.4 on 2021-12-12 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0022_user_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter_email', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='resource',
            name='down_vote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='down_vote', to='form.vote'),
        ),
        migrations.AddField(
            model_name='resource',
            name='up_vote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='up_vote', to='form.vote'),
        ),
    ]
