# Generated by Django 3.2.4 on 2021-12-04 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0022_user_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='num_vote_down',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='resource',
            name='num_vote_up',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='resource',
            name='vote_score',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
