# Generated by Django 3.2.4 on 2021-12-12 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0023_auto_20211212_2350'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='vote_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
