# Generated by Django 3.2.4 on 2021-12-12 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0024_resource_vote_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='vote_score',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
