# Generated by Django 3.2.5 on 2021-12-05 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0025_auto_20211205_1622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='num_vote_down',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='num_vote_up',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='vote_score',
        ),
    ]
