# Generated by Django 3.2.5 on 2021-12-05 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0029_auto_20211205_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likedislike',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='form.user', verbose_name='vote'),
        ),
        migrations.AlterField(
            model_name='likedislike',
            name='vote',
            field=models.SmallIntegerField(blank=True, choices=[(-1, 'Dislike'), (1, 'Like')], verbose_name='user'),
        ),
    ]
