# Generated by Django 3.2.5 on 2021-12-05 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0030_auto_20211205_2213'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.IntegerField(blank=True, default=0)),
                ('dislike', models.IntegerField(blank=True, default=0)),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='form.user')),
            ],
        ),
        migrations.DeleteModel(
            name='LikeDislike',
        ),
        migrations.AddField(
            model_name='resource',
            name='vote',
            field=models.OneToOneField(blank=True, default=0, on_delete=django.db.models.deletion.PROTECT, related_name='vote_resource', to='form.vote'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subtopic',
            name='vote',
            field=models.OneToOneField(blank=True, default=0, on_delete=django.db.models.deletion.PROTECT, related_name='vote_subtopic', to='form.vote'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topic',
            name='vote',
            field=models.OneToOneField(blank=True, default=0, on_delete=django.db.models.deletion.PROTECT, related_name='vote_topic', to='form.vote'),
            preserve_default=False,
        ),
    ]
