# Generated by Django 3.2.5 on 2021-12-06 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0031_auto_20211205_2238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='id',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='vote',
        ),
        migrations.RemoveField(
            model_name='subtopic',
            name='id',
        ),
        migrations.RemoveField(
            model_name='subtopic',
            name='vote',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='vote',
        ),
        migrations.AddField(
            model_name='resource',
            name='resource_vote',
            field=models.OneToOneField(blank=True, default=0, on_delete=django.db.models.deletion.PROTECT, parent_link=True, primary_key=True, related_name='vote_resource', serialize=False, to='form.vote'),
        ),
        migrations.AddField(
            model_name='subtopic',
            name='subtopic_vote',
            field=models.OneToOneField(blank=True, default=0, on_delete=django.db.models.deletion.PROTECT, parent_link=True, primary_key=True, related_name='vote_subtopic', serialize=False, to='form.vote'),
        ),
        migrations.AddField(
            model_name='topic',
            name='topic_vote',
            field=models.OneToOneField(blank=True, default=0, on_delete=django.db.models.deletion.PROTECT, parent_link=True, related_name='vote_topic', to='form.vote'),
        ),
    ]
