# Generated by Django 3.2.5 on 2021-12-06 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0032_auto_20211206_1939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='user',
        ),
    ]
