# Generated by Django 3.2.4 on 2022-01-24 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0036_auto_20220125_0207'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prerequisite',
            options={'ordering': ('order',)},
        ),
        migrations.AlterModelOptions(
            name='subtopic',
            options={'ordering': ('order',)},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ('order',)},
        ),
        migrations.AlterModelOptions(
            name='user_messages',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='prerequisite',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False, verbose_name='order'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subtopic',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False, verbose_name='order'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topic',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False, verbose_name='order'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_messages',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False, verbose_name='order'),
            preserve_default=False,
        ),
    ]
